name: Push

on:
  push:
    branches: ["main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'zulu'
            cache: gradle

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
          working-directory: ./chapterfourteen
         
        - name: Build with Gradle
          run: ./gradlew bundleRelease
          working-directory: ./chapterfourteen

        - name: Run ktlintFormat
          run: ./gradlew ktlintFormat
          working-directory: ./chapterfourteen

        - name: Run ktlintCheck
          run: ./gradlew ktlintCheck
          working-directory: ./chapterfourteen

        - name: Run detekt
          run: ./gradlew detekt
          working-directory: ./chapterfourteen

        - name: Run unit tests
          run: ./gradlew test
          working-directory: ./chapterfourteen

        - name: Run connected tests
          uses: ReactiveCircus/android-emulator-runner@v2
          with:
            working-directory: ./chapterfourteen
            api-level: 33
            target: google_apis
            arch: x86_64
            disable-animations: true
            script: ./gradlew connectedCheck
          
    
